//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Tomorrow.Train {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrainTimeWebServiceSoap", Namespace="http://WebXml.com.cn/")]
    public partial class TrainTimeWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getStationNameDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStationAndTimeByTrainCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVersionTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStationAndTimeDataSetByTrainCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStationAndTimeDataSetByLikeTrainCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDetailInfoByTrainCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStationNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStationAndTimeByStationNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrainTimeWebService() {
            this.Url = global::Tomorrow.Properties.Settings.Default.Tomorrow_cn_com_webxml_www2_TrainTimeWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getStationNameDataSetCompletedEventHandler getStationNameDataSetCompleted;
        
        /// <remarks/>
        public event getStationAndTimeByTrainCodeCompletedEventHandler getStationAndTimeByTrainCodeCompleted;
        
        /// <remarks/>
        public event getVersionTimeCompletedEventHandler getVersionTimeCompleted;
        
        /// <remarks/>
        public event getStationAndTimeDataSetByTrainCodeCompletedEventHandler getStationAndTimeDataSetByTrainCodeCompleted;
        
        /// <remarks/>
        public event getStationAndTimeDataSetByLikeTrainCodeCompletedEventHandler getStationAndTimeDataSetByLikeTrainCodeCompleted;
        
        /// <remarks/>
        public event getDetailInfoByTrainCodeCompletedEventHandler getDetailInfoByTrainCodeCompleted;
        
        /// <remarks/>
        public event getStationNameCompletedEventHandler getStationNameCompleted;
        
        /// <remarks/>
        public event getStationAndTimeByStationNameCompletedEventHandler getStationAndTimeByStationNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStationNameDataSet", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getStationNameDataSet() {
            object[] results = this.Invoke("getStationNameDataSet", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getStationNameDataSetAsync() {
            this.getStationNameDataSetAsync(null);
        }
        
        /// <remarks/>
        public void getStationNameDataSetAsync(object userState) {
            if ((this.getStationNameDataSetOperationCompleted == null)) {
                this.getStationNameDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStationNameDataSetOperationCompleted);
            }
            this.InvokeAsync("getStationNameDataSet", new object[0], this.getStationNameDataSetOperationCompleted, userState);
        }
        
        private void OngetStationNameDataSetOperationCompleted(object arg) {
            if ((this.getStationNameDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStationNameDataSetCompleted(this, new getStationNameDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStationAndTimeByTrainCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getStationAndTimeByTrainCode(string TrainCode, string UserID) {
            object[] results = this.Invoke("getStationAndTimeByTrainCode", new object[] {
                        TrainCode,
                        UserID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getStationAndTimeByTrainCodeAsync(string TrainCode, string UserID) {
            this.getStationAndTimeByTrainCodeAsync(TrainCode, UserID, null);
        }
        
        /// <remarks/>
        public void getStationAndTimeByTrainCodeAsync(string TrainCode, string UserID, object userState) {
            if ((this.getStationAndTimeByTrainCodeOperationCompleted == null)) {
                this.getStationAndTimeByTrainCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStationAndTimeByTrainCodeOperationCompleted);
            }
            this.InvokeAsync("getStationAndTimeByTrainCode", new object[] {
                        TrainCode,
                        UserID}, this.getStationAndTimeByTrainCodeOperationCompleted, userState);
        }
        
        private void OngetStationAndTimeByTrainCodeOperationCompleted(object arg) {
            if ((this.getStationAndTimeByTrainCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStationAndTimeByTrainCodeCompleted(this, new getStationAndTimeByTrainCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getVersionTime", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getVersionTime() {
            object[] results = this.Invoke("getVersionTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVersionTimeAsync() {
            this.getVersionTimeAsync(null);
        }
        
        /// <remarks/>
        public void getVersionTimeAsync(object userState) {
            if ((this.getVersionTimeOperationCompleted == null)) {
                this.getVersionTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVersionTimeOperationCompleted);
            }
            this.InvokeAsync("getVersionTime", new object[0], this.getVersionTimeOperationCompleted, userState);
        }
        
        private void OngetVersionTimeOperationCompleted(object arg) {
            if ((this.getVersionTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVersionTimeCompleted(this, new getVersionTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStationAndTimeDataSetByTrainCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getStationAndTimeDataSetByTrainCode(string TrainCode, string UserID) {
            object[] results = this.Invoke("getStationAndTimeDataSetByTrainCode", new object[] {
                        TrainCode,
                        UserID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getStationAndTimeDataSetByTrainCodeAsync(string TrainCode, string UserID) {
            this.getStationAndTimeDataSetByTrainCodeAsync(TrainCode, UserID, null);
        }
        
        /// <remarks/>
        public void getStationAndTimeDataSetByTrainCodeAsync(string TrainCode, string UserID, object userState) {
            if ((this.getStationAndTimeDataSetByTrainCodeOperationCompleted == null)) {
                this.getStationAndTimeDataSetByTrainCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStationAndTimeDataSetByTrainCodeOperationCompleted);
            }
            this.InvokeAsync("getStationAndTimeDataSetByTrainCode", new object[] {
                        TrainCode,
                        UserID}, this.getStationAndTimeDataSetByTrainCodeOperationCompleted, userState);
        }
        
        private void OngetStationAndTimeDataSetByTrainCodeOperationCompleted(object arg) {
            if ((this.getStationAndTimeDataSetByTrainCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStationAndTimeDataSetByTrainCodeCompleted(this, new getStationAndTimeDataSetByTrainCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStationAndTimeDataSetByLikeTrainCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getStationAndTimeDataSetByLikeTrainCode(string TrainCode, string UserID) {
            object[] results = this.Invoke("getStationAndTimeDataSetByLikeTrainCode", new object[] {
                        TrainCode,
                        UserID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getStationAndTimeDataSetByLikeTrainCodeAsync(string TrainCode, string UserID) {
            this.getStationAndTimeDataSetByLikeTrainCodeAsync(TrainCode, UserID, null);
        }
        
        /// <remarks/>
        public void getStationAndTimeDataSetByLikeTrainCodeAsync(string TrainCode, string UserID, object userState) {
            if ((this.getStationAndTimeDataSetByLikeTrainCodeOperationCompleted == null)) {
                this.getStationAndTimeDataSetByLikeTrainCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStationAndTimeDataSetByLikeTrainCodeOperationCompleted);
            }
            this.InvokeAsync("getStationAndTimeDataSetByLikeTrainCode", new object[] {
                        TrainCode,
                        UserID}, this.getStationAndTimeDataSetByLikeTrainCodeOperationCompleted, userState);
        }
        
        private void OngetStationAndTimeDataSetByLikeTrainCodeOperationCompleted(object arg) {
            if ((this.getStationAndTimeDataSetByLikeTrainCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStationAndTimeDataSetByLikeTrainCodeCompleted(this, new getStationAndTimeDataSetByLikeTrainCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getDetailInfoByTrainCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDetailInfoByTrainCode(string TrainCode, string UserID) {
            object[] results = this.Invoke("getDetailInfoByTrainCode", new object[] {
                        TrainCode,
                        UserID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDetailInfoByTrainCodeAsync(string TrainCode, string UserID) {
            this.getDetailInfoByTrainCodeAsync(TrainCode, UserID, null);
        }
        
        /// <remarks/>
        public void getDetailInfoByTrainCodeAsync(string TrainCode, string UserID, object userState) {
            if ((this.getDetailInfoByTrainCodeOperationCompleted == null)) {
                this.getDetailInfoByTrainCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDetailInfoByTrainCodeOperationCompleted);
            }
            this.InvokeAsync("getDetailInfoByTrainCode", new object[] {
                        TrainCode,
                        UserID}, this.getDetailInfoByTrainCodeOperationCompleted, userState);
        }
        
        private void OngetDetailInfoByTrainCodeOperationCompleted(object arg) {
            if ((this.getDetailInfoByTrainCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDetailInfoByTrainCodeCompleted(this, new getDetailInfoByTrainCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStationName", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getStationName() {
            object[] results = this.Invoke("getStationName", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getStationNameAsync() {
            this.getStationNameAsync(null);
        }
        
        /// <remarks/>
        public void getStationNameAsync(object userState) {
            if ((this.getStationNameOperationCompleted == null)) {
                this.getStationNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStationNameOperationCompleted);
            }
            this.InvokeAsync("getStationName", new object[0], this.getStationNameOperationCompleted, userState);
        }
        
        private void OngetStationNameOperationCompleted(object arg) {
            if ((this.getStationNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStationNameCompleted(this, new getStationNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStationAndTimeByStationName", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getStationAndTimeByStationName(string StartStation, string ArriveStation, string UserID) {
            object[] results = this.Invoke("getStationAndTimeByStationName", new object[] {
                        StartStation,
                        ArriveStation,
                        UserID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getStationAndTimeByStationNameAsync(string StartStation, string ArriveStation, string UserID) {
            this.getStationAndTimeByStationNameAsync(StartStation, ArriveStation, UserID, null);
        }
        
        /// <remarks/>
        public void getStationAndTimeByStationNameAsync(string StartStation, string ArriveStation, string UserID, object userState) {
            if ((this.getStationAndTimeByStationNameOperationCompleted == null)) {
                this.getStationAndTimeByStationNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStationAndTimeByStationNameOperationCompleted);
            }
            this.InvokeAsync("getStationAndTimeByStationName", new object[] {
                        StartStation,
                        ArriveStation,
                        UserID}, this.getStationAndTimeByStationNameOperationCompleted, userState);
        }
        
        private void OngetStationAndTimeByStationNameOperationCompleted(object arg) {
            if ((this.getStationAndTimeByStationNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStationAndTimeByStationNameCompleted(this, new getStationAndTimeByStationNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getStationNameDataSetCompletedEventHandler(object sender, getStationNameDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStationNameDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStationNameDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getStationAndTimeByTrainCodeCompletedEventHandler(object sender, getStationAndTimeByTrainCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStationAndTimeByTrainCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStationAndTimeByTrainCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getVersionTimeCompletedEventHandler(object sender, getVersionTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVersionTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVersionTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getStationAndTimeDataSetByTrainCodeCompletedEventHandler(object sender, getStationAndTimeDataSetByTrainCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStationAndTimeDataSetByTrainCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStationAndTimeDataSetByTrainCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getStationAndTimeDataSetByLikeTrainCodeCompletedEventHandler(object sender, getStationAndTimeDataSetByLikeTrainCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStationAndTimeDataSetByLikeTrainCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStationAndTimeDataSetByLikeTrainCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getDetailInfoByTrainCodeCompletedEventHandler(object sender, getDetailInfoByTrainCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDetailInfoByTrainCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDetailInfoByTrainCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getStationNameCompletedEventHandler(object sender, getStationNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStationNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStationNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getStationAndTimeByStationNameCompletedEventHandler(object sender, getStationAndTimeByStationNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStationAndTimeByStationNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStationAndTimeByStationNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591